apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-vznzyvsc
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/tsscui/backend-tests-go-vznzyvsc:29464b76ab0f263353487b03d6f7583f4dd6c21d
        name: container-image  
